### PR TITLE
Also build docker image for arm64

### PR DESCRIPTION
**Pull request by karuboniru**
so people can run this in their rpi

### CODE REVIEW

**Comment by URenko** [comment]
Does your 7-zip support rar?
(you can check it with `7zz i`)

**Comment by URenko** [comment]
I noticed "Add libjxl support once in stable" is in the TODO list of https://github.com/wader/static-ffmpeg/blob/master/README.md
I'm afraid we need to wait it or choose another build.

**Comment by karuboniru** [comment]
Now we get fffmpeg w/ libjxl

**Comment by URenko** [comment]
Excellent!

**Pull request merged**
